"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import type { AiPrompt } from "@/types";
import { MODELS_LIST } from "../../components/models-list";

interface PromptFormDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  initialData?: AiPrompt | null;
}

export function PromptFormDialog({
  open,
  onOpenChange,
  initialData,
}: PromptFormDialogProps) {
  const [title, setTitle] = useState(initialData?.title ?? "");
  const [promptText, setPromptText] = useState(initialData?.promptText ?? "");
  const [model, setModel] = useState(initialData?.model ?? "");

  const handleSave = () => {
    // Placeholder for actual save logic
    console.log("Saving...", { title, promptText, model });
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-125">
        <DialogHeader>
          <DialogTitle>
            {initialData ? "Edit Prompt" : "Add New Prompt"}
          </DialogTitle>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="title">Title</Label>
            <Input
              id="title"
              placeholder="e.g., Cyberpunk Cityscape"
              className="bg-primary-foreground"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="model">AI Model</Label>
            <Select value={model} onValueChange={setModel}>
              <SelectTrigger className="bg-primary-foreground">
                <SelectValue placeholder="Select a model" />
              </SelectTrigger>
              <SelectContent className="bg-primary-foreground">
                {MODELS_LIST.map((model) => (
                  <SelectItem key={model.slug} value={model.slug}>
                    {model.icon}
                    {model.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="prompt">Prompt</Label>
            <Textarea
              id="prompt"
              placeholder="Enter your full prompt here..."
              className="bg-primary-foreground h-32 resize-none"
              value={promptText}
              onChange={(e) => setPromptText(e.target.value)}
            />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="image">Example Image</Label>
            <Input
              id="image"
              type="file"
              accept="image/*"
              className="bg-primary-foreground cursor-pointer"
            />
            <p className="text-muted-foreground text-xs">
              Upload an image generated by this prompt.
            </p>
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleSave}>Save Prompt</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
